name: Petshop serverless

on:
  push:

jobs:

  build:
    runs-on: self-hosted # windows-2019

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1 
      with:
        login-server: ${{ secrets.REGISTRY_USERNAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t pieterd.azurecr.io/petshop:${{ github.sha }} -f ./docker/web/Dockerfile
        docker push pieterd.azurecr.io/petshop:${{ github.sha }}
